### ISSUE TITLE
Terminal output

### ISSUE THREAD

**Issue by prohtex** [RJVB/DropScript#2]
Thanks so much for this very useful package! I've used DropScript to turn a whole bunch of frequently used scripts into drag and drop apps. I was wondering if anybody had ideas for handling command line output? I guess I could use AppleScript to open a terminal window and then execute an external script from there, closing the window when it finishes?

**Comment by RJVB** [comment]
What would you want to do with the script output?

**Comment by prohtex** [comment]
Display it in a terminal window while the script is running.

**Comment by RJVB** [comment]
You can also do something like (provided you don't need interaction with the script):

```
> touch $TMPDIR/$scriptname.log
> open $TMPDIR/$scriptname.log
> $scriptname >> $TMPDIR/$scriptname.log
```

With that you'd only need to use AppleScript to tell Console.app to quit or close the output window.

**Comment by prohtex** [comment]
I did try that, but the output is also used as a progress indicator. I was wondering if anybody else had tried to show live output one way or another. I guess I could also do something like "tail -f" on the log file ? Seems like an applescript solution might be simpler?

**Comment by prohtex** [comment]
Here is a small script that simply obtains the working dir (so another script can be executed in a Terminal window) and tries to get the passed vars. For some reason I can't access the vars!

`#!/usr/bin/osascript`

set MyPath to POSIX path of ((path to me as text) & "::")
set MyTarget to POSIX path of item 1 of argv
Tell Application "Terminal"
	activate
	do script "ls " & MyTarget
end Tell`

**Comment by prohtex** [comment]
Also, I noticed in the app bundle there is a shell script that seems to use osascript to open a Terminal window. Would I be able to use this instead?

**Comment by prohtex** [comment]
I've solved my own problem - maybe someone else will find this useful. In place of the drop_script that is typically run from the app bundle, I have 2 scripts: drop_script and my_script. drop_script is an applescript that determines the CWD, accepts the command line args (dropped files), then executes my_script in a terminal window, passing along the args. Is this a little silly? Sure, but it allows me to drag files to an app in the Finder, then run a shell script with live output, accepting those files as args. Very useful.

drop_script

    #!/usr/bin/osascript
    
    on Run argv
    	if (count of argv > 0) then
    		set MyPath to POSIX path of ((path to me as text) & "::")
    		set MyTarget to POSIX path of item 1 of argv
    		Tell Application "Terminal"
    			activate
    			do script MyPath & "my_script " & "'" & MyTarget & "'"
    		end Tell
    	else
    		display dialog "You did not drop any files" giving up after 5
    	end if
    end Run

my_script (as an example, lists contents of a dropped dir)

    #!/bin/bash
    
    ls "$1"

**Comment by RJVB** [comment]
That's the next thing I would have suggested.
I think though that you should be able to do this without AppleScript. I don't have access to a Mac for a while, but you can tell Terminal.app to launch a script from the commandline. IOW, you should at least be able to use a shell script instead of an AppleScript launcher, for instance

```
#!/bin/sh

SCRIPT="${TMPDIR}/RunInTerminal.$$.sh"

CleanUp() {
        rm -f "${SCRIPT}"
}

trap CleanUp 0
trap CleanUp 1
trap CleanUp 2
trap CleanUp 15

if [ $# != 0 ] ;then
        echo "$@" > "${SCRIPT}"
else
        cat - > "${SCRIPT}"
fi
chmod 700 "${SCRIPT}"

echo "Running the requested command(s) in a new Terminal instance"
echo "Remember to quit the Terminal application!"

open -W -n -F -a Terminal.app "${SCRIPT}"
```

And you could experiment with the script interpreter:

```
#!/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal ...
```

or using /usr/bin/open with the appropriate arguments.
